# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'Flash Chat iOS13' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Add pods for desired Firebase products
  # https://firebase.google.com/docs/ios/setup#available-pods
  
  # Pods for Flash Chat iOS13
  pod 'SVProgressHUD'
  pod 'IQKeyboardManager'
  pod 'Firebase/Auth'
  pod 'Firebase/Firestore'

end
